services:
  app:
    image: "${APP_IMAGE:?APP_IMAGE requis}"
    container_name: busstation-backend
    restart: unless-stopped
    env_file: [.env]
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:8080/actuator/health >/dev/null 2>&1 || wget -qO- http://127.0.0.1:8080/ >/dev/null 2>&1; [ $? -le 8 ] && exit 0 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.busstation.rule=Host(`busstation.yowyob.com`) && PathPrefix(`/station-api`)"
      - "traefik.http.middlewares.busstation-strip.stripprefix.prefixes=/station-api"
      - "traefik.http.routers.busstation.middlewares=busstation-strip"
      - "traefik.http.routers.busstation.entrypoints=websecure"
      - "traefik.http.routers.busstation.tls=true"
      - "traefik.http.routers.busstation.tls.certresolver=letsencrypt"
      - "traefik.http.services.busstation.loadbalancer.server.port=8080"
      - "traefik.docker.network=yowyob"
    networks: [yowyob]
networks:
  yowyob: { external: true, name: yowyob }
